### ISSUE TITLE
On dragging block content change from number to word (eg. 1 -> One) in "Sort in Stack Game"

### ISSUE THREAD

**Issue by alii13** [alejandrosobko/tikijuegos#11]
Here is the screenshot for reference
Before Starting of Game - 
![issue_before](https://user-images.githubusercontent.com/48530814/94468750-904af400-01e2-11eb-99b6-cbc864592e94.png)

After Dragging a block -
![issue](https://user-images.githubusercontent.com/48530814/94468854-b2447680-01e2-11eb-91c1-a4b41f7ea711.png)

**Comment by alejandrosobko** [comment]
Hi @alii13 thanks for creating an issue. 
Do you have steps to reproduce it? I tried by playing but I couldn't see the letters as you mentioned.
Browser?

**Comment by alii13** [comment]
Hey, @alejandrosobko I just checked the website this time everything works as expected, I don't know why it was misbehaving yesterday.

**Comment by alii13** [comment]
Okay, I got the answer why it was misbehaving yesterday..
When I switched the language in your site from Spanish to English using google translator in the search tab. It is giving the above results which are in the screenshot. I don't know why it is 1st & 2nd block only :/

**Comment by alejandrosobko** [comment]
@alii13 good catch! So it seems to be Google Translator trying to translate the buttons. Good thing is I have pending the ticket to add I18N to the site :)
